name: Update Toc

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天的 0 点执行

jobs:
  update_directory_tree:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name "NowScott"
        git config --global user.email "nowscott@qq.com"
        git clone https://github.com/nowscott/NowStrideUp.git
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run toc.py
      run: python toc.py

    - name: Commit and push changes to README.md
      run: |
        filename="README.md"
        if ! git diff --quiet --exit-code; then
          git add $filename
          git commit -m "Update README.md by GitHub Action"
          git push
        else
          echo "没有变化。"
        fi
